Public Partial Class ErrorPage
    Protected Head1 As Global.System.Web.UI.HtmlControls.HtmlHead
    Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected ApplicationTitle As Global.System.Web.UI.WebControls.Literal
    Protected InfoMessagesPanel As Global.System.Web.UI.WebControls.Literal
    Protected Table1 As Global.System.Web.UI.WebControls.Table
    Protected TableRow2 As Global.System.Web.UI.WebControls.TableRow
    Protected ViewSite As Global.System.Web.UI.WebControls.TableCell
    Protected ErrorTitleLiteral As Global.System.Web.UI.WebControls.Literal
    Protected ErrorPanel As Global.System.Web.UI.WebControls.Panel
    Protected ReportResult As Global.System.Web.UI.WebControls.PlaceHolder
    Protected ApologizeMessage As Global.System.Web.UI.WebControls.PlaceHolder
    Protected HyperLink1 As Global.System.Web.UI.WebControls.HyperLink
    Protected NavigateToStart As Global.System.Web.UI.WebControls.LinkButton
    Protected PopupReportResult As Global.System.Web.UI.WebControls.PlaceHolder
    Protected PopupApologizeMessage As Global.System.Web.UI.WebControls.PlaceHolder
    Protected HyperLink2 As Global.System.Web.UI.WebControls.HyperLink
    Protected Details As Global.System.Web.UI.WebControls.Panel
    Protected DetailsText As Global.System.Web.UI.WebControls.Literal
    Protected ReportForm As Global.System.Web.UI.WebControls.Panel
    Protected DescriptionTextBox As Global.System.Web.UI.WebControls.TextBox
    Protected ReportButton As Global.System.Web.UI.WebControls.Button
End Class
